# Generated by Django 4.0.2 on 2022-03-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='dob',
        ),
    ]
