# Generated by Django 4.0.2 on 2022-04-17 00:51

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File'),
        ),
    ]
