# Generated by Django 4.0.2 on 2022-04-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
