# Generated by Django 4.0.2 on 2022-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_remove_candidates_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
