# Generated by Django 4.0.2 on 2022-03-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_candidates_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
