# Generated by Django 4.0.2 on 2022-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_candidate_email_notification_delete_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
