# Generated by Django 4.0.2 on 2022-03-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_auto_20200906_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='company',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
