# Generated by Django 4.0.2 on 2022-04-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0006_alter_jobs_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='is_company',
        ),
    ]
