# Generated by Django 4.0.2 on 2022-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_recruiter_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, to='JobPortal.Jobs'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='JobPortal.Candidates'),
        ),
    ]
